CREATE TABLE urls (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    created_at TIMESTAMP NOT NULL NOW()
);

CREATE TABLE url_checks (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    url_id INT NOT NULL REFERENCES urls (id),
    status_code INT,
    h1 VARCHAR(255),
    title VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP NOT NULL NOW()
);